version: 0.0
os: linux
files:
  - source: .
    destination: /aws_flask/
hooks:
  BeforeInstall: # 安装依赖模块
    - location: before_install.sh
  AfterInstall: # 配置服务
    - location: after_install.sh
      timeout: 180
  ApplicationStart: # 开始服务的脚本
    - location: start_uwsgi.sh
    - location: start_nginx.sh
      timeout: 300
      runas: root
  ApplicationStop: # 停止服务的脚本
    - location: stop_uwsgi.sh
    - location: stop_nginx.sh
      timeout: 300
      runas: root